#server setting
server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8
    
    
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/boot1?characterEncoding=utf8&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/boot1?characterEncoding=utf8&serverTimezone=Hongkong
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
  #Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    database: 1
    host: 192.168.8.162
    port: 6379
    password:
    pool:
      #连接池中的最大空闲连接
      max-idle: 8
      min-idle: 0
      #连接池最大连接数(使用负值表示没有限制)
      max-active: 8
      #连接池最大阻塞等待时间(使用负值表示没有限制)
      max-wait: -1
        
        
        